//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rand9er.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rand9er.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bgc {
            get {
                object obj = ResourceManager.GetObject("bgc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bgc2 {
            get {
                object obj = ResourceManager.GetObject("bgc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sbag3 {
            get {
                object obj = ResourceManager.GetObject("sbag3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stilzkin {
            get {
                object obj = ResourceManager.GetObject("stilzkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;EnemyFolder&quot;:&quot;\\StreamingAssets\\assets\\resources\\battlemap\\battlescene\\evt_battle_ac_e028f\\dbfile0000.raw16.bytes&quot;,&quot;EnemyBytes&quot;:&quot;BwYCByEAAAAKAgAAAQAAAAABAAD0AQAAkAEAAAABAAAM/gAAkAEAAAEBAADoAwAA6AMAAAEBAADoAwAAvAIAAA8DAQACAAAAAAEAALwCAACQAQAAAAEAAAAAAADoAwAAAAEAAET9AAAgAwAAAQEAABj8AACKAgAADwQCAAMAAAAAAQAABAQAANABAAAAAQAArAEAADAGAAAAAQAA1P0AAFAGAAAAAQAA/PoAADAFAAAoAwEAAgAAAAABAACEAwAAkAEAAAEBAAAAAAAAvAIAAAABAAB8/AAA6AMAAAEBAAB8/AAAkAEAAAoCAgACAAAAAQEAALwCAACEAwAAAQEAAET9AACQAQAAAAEAABj8AACQAQAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StockEnemyBytesJsonNoZeros {
            get {
                return ResourceManager.GetString("StockEnemyBytesJsonNoZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yuno_error {
            get {
                object obj = ResourceManager.GetObject("yuno_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
